### ISSUE TITLE
ERROR here

### ISSUE THREAD

**Issue by hubertkumpel** [Phoenixx19/JumpKingPlus#5]
I installed JK plus properly and this happened when i open JK 
![image](https://user-images.githubusercontent.com/69690507/121813946-bfb96800-cc6e-11eb-8d71-003a9a1b2b94.png)
Help plz !

**Comment by Phoenixx19** [comment]
Known problem, known fix.
Delete your controller binds (they are .xml files inside: `Jump King/Content/ControllerBinds`).

Let me know if it works.
