### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by Pokken1** [Phoenixx19/JumpKingPlus#8]
![image](https://user-images.githubusercontent.com/89053331/129648697-ae1570d9-896c-49e3-b034-b60d4ce77e78.png)
I tried installing Babe of Ascension but messed up. I tried uninstalling and reinstalling Jump King as well as Jump King Plus. I don't know what to do.

**Comment by Phoenixx19** [comment]
Have you followed the tutorial on how to install the custom levels?
It seems to me that you might have replaced the game files with the custom level, but I might be wrong.

**Comment by Pokken1** [comment]
No, I didn't. Can you share with me a video tutorial on how to install the
map correctly? I might have done that.

**Comment by Phoenixx19** [comment]
Here you go, both videos here.
https://www.youtube.com/watch?v=kxg3U3plg8s&list=PLfY0-4XVicY9Fn-kw73cGq_dzQyHdl3IC

**Comment by Pokken1** [comment]
TYSM!!!
