### ISSUE TITLE
Babe of Ascension problem with bird

### ISSUE THREAD

**Issue by Rifremore** [Phoenixx19/JumpKingPlus#9]
Hi,
I've recently (yesterday) ended Babe of Ascension and I have one question.
On the screens from the game on the main page of the Babe of Ascension (this link: https://phoenixx19.github.io/JumpKingPlus/workshop/3/) you can see the main character wearing a black cap (looking similiar to a "Golden Cap" from Ghost of the Babe). At the end of "The Nest" you can start chasing this bird. I've ended this secret room and started chasing away this bird (It's toucan, I guess). I've chased him up to a last screen. I've got a golden ring from him and he flew away. I was thinking that I will get this cap in the cutscene, like in the Ghost of the Babe I got "King's Cape". I've finished the game and a cutscene has changed: instead of two angels (or something i don't know what it is), a bird flew up, but not the one I was chasing, but the raven from the main story. I've received a crown from him, but as he flew away,  texture of it changed into toucan, which i was chasing, but cutscene didn't changed anymore and I just flew away with the princess. And here is my question: I should receive something more from this bird in the cutscene (like this black cap) and it is a bug? If it's a bug, I will do it again after introducing bugfix, bcs this cap looks nice. I don't have any records from it and I haven't seen anywhere anyone who chased this toucan to the top.
At the end, I've wanted to sorry for my english, but I'm still learning this language.

**Comment by Phoenixx19** [comment]
From what I remember, the cap has been (in _late development_) **removed** from the map. I'm sure you'll get the cap soon! I'm finishing a skin-related update, so it might not take that long to get it!
